# werbicki.github.io

title: Paul's Notes
description: >- # this means to ignore newlines until "baseurl:"
  Random notes on deep dives into truly meaningless efforts that make me happy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/Computer.png"

# https://github.com/mmistakes/so-simple-theme
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

# Site Author
author:
  name: Paul Werbicki
  picture: /assets/images/Fo5hWasHereInvaders.png
  email: werbicki@criticaljunction.com

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://ca.linkedin.com/in/paul-werbicki-a524bb1
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/werbicki
    icon: fab fa-github-square

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
